# Basic example

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


data is 1000 x 100 array

In [2]:
data = np.random.random((1000,100))
data.shape

(1000, 100)

In [3]:
data

array([[ 0.42536932,  0.29156014,  0.24796293, ...,  0.00734982,
         0.67409077,  0.15762147],
       [ 0.61609748,  0.44411782,  0.34262964, ...,  0.69733272,
         0.14961597,  0.9761147 ],
       [ 0.6618984 ,  0.20751003,  0.03502032, ...,  0.27879601,
         0.0223021 ,  0.20347569],
       ..., 
       [ 0.47964497,  0.00992871,  0.97224742, ...,  0.70682668,
         0.93216782,  0.60291315],
       [ 0.80692483,  0.23948212,  0.33379203, ...,  0.11201047,
         0.19864018,  0.53805665],
       [ 0.06832245,  0.79812478,  0.37335088, ...,  0.2942097 ,
         0.06730854,  0.00447   ]])

Generate 1000 x 1 array of ints between 0 and 1

In [4]:
labels = np.random.randint(2, size=(1000, 1))
labels.shape

(1000, 1)

In [5]:
print(dir(Sequential))

['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_add_inbound_node', '_base_init', '_check_trainable_weights_consistency', '_get_node_attribute_at_index', '_init_graph_network', '_init_subclassed_network', '_make_predict_function', '_make_test_function', '_make_train_function', '_node_key', '_set_inputs', '_standardize_user_data', '_updated_config', '_uses_dynamic_learning_phase', 'add', 'add_loss', 'add_update', 'add_weight', 'assert_input_compatibility', 'build', 'built', 'call', 'compile', 'compute_mask', 'compute_output_shape', 'count_params', 'evaluate', 'evaluate_generator', 'fit', 'fit_generator', 'from_config', 'get_config', 'get_input_at', 'get_input_mask_at', 'get_input_sh

In [6]:
print(Sequential.__doc__)

Linear stack of layers.

    # Arguments
        layers: list of layers to add to the model.

    # Example

    ```python
    # Optionally, the first layer can receive an `input_shape` argument:
    model = Sequential()
    model.add(Dense(32, input_shape=(500,)))

    # Afterwards, we do automatic shape inference:
    model.add(Dense(32))

    # This is identical to the following:
    model = Sequential()
    model.add(Dense(32, input_dim=500))

    # And to the following:
    model = Sequential()
    model.add(Dense(32, batch_input_shape=(None, 500)))

    # Note that you can also omit the `input_shape` argument:
    # In that case the model gets built the first time you call `fit` (or other
    # training and evaluation methods).
    model = Sequential()
    model.add(Dense(32))
    model.add(Dense(32))
    model.compile(optimizer=optimizer, loss=loss)

    # This builds the model for the first time:
    model.fit(x, y, batch_size=32, epochs=10)

    # Note that when using this del

- 1000 x 100 array means 100 columns/features
- https://www.analyticsvidhya.com/blog/2017/10/fundamentals-deep-learning-activation-functions-when-to-use-them/
- https://towardsdatascience.com/exploring-activation-functions-for-neural-networks-73498da59b02
- http://ruder.io/optimizing-gradient-descent/
- https://en.wikipedia.org/wiki/Loss_function

In [7]:
model = Sequential()
# Rectified Linear Unit
model.add(Dense(32, activation='relu', input_dim=100))
# Sigmoid activation function
model.add(Dense(1, activation='sigmoid'))

# Divides the learning rate by an exponentially decaying average of squared gradients
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(data, labels, epochs=10, batch_size=32)
prediction = model.predict(data)

Epoch 1/10
1000/1000 [==============================] - 0s 74us/step - loss: 0.7139 - acc: 0.4920
Epoch 2/10
1000/1000 [==============================] - 0s 82us/step - loss: 0.7022 - acc: 0.5290
Epoch 3/10
1000/1000 [==============================] - 0s 74us/step - loss: 0.6946 - acc: 0.5470
Epoch 4/10
1000/1000 [==============================] - 0s 74us/step - loss: 0.6914 - acc: 0.5490
Epoch 5/10
1000/1000 [==============================] - 0s 82us/step - loss: 0.6863 - acc: 0.5630
Epoch 6/10
1000/1000 [==============================] - 0s 102us/step - loss: 0.6830 - acc: 0.5500
Epoch 7/10
1000/1000 [==============================] - 0s 116us/step - loss: 0.6793 - acc: 0.5620
Epoch 8/10
1000/1000 [==============================] - 0s 85us/step - loss: 0.6742 - acc: 0.5640
Epoch 9/10
1000/1000 [==============================] - 0s 82us/step - loss: 0.6729 - acc: 0.5840
Epoch 10/10
1000/1000 [==============================] - 0s 108us/step - loss: 0.6655 - acc: 0.5900


In [8]:
prediction.shape

(1000, 1)

# Data
- https://keras.io/datasets/#datasets

In [9]:
from keras.datasets import boston_housing, mnist, cifar10, imdb

In [10]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
(x_train2, y_train2), (x_test2, y_test2) = boston_housing.load_data()
(x_train3, y_train3), (x_test3, y_test3) = cifar10.load_data()
(x_train4, y_train4), (x_test4, y_test4) = imdb.load_data(num_words=20000)
num_classes = 10

17465344/17464789 [==============================] - 21s 1us/step


In [11]:
x_train.shape, y_train.shape

((60000, 28, 28), (60000,))

In [12]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

# Preprocessing
## Sequence padding

In [13]:
from keras.preprocessing import sequence

In [14]:
x_train4.shape

(25000,)

In [15]:
x_train4

array([ [1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32],
       [1, 194, 1153, 194, 8255, 78, 22

In [16]:
x_train4 = sequence.pad_sequences(x_train4, maxlen=80)
x_train4.shape

(25000, 80)

In [17]:
x_train4

array([[   15,   256,     4, ...,    19,   178,    32],
       [  125,    68,     2, ...,    16,   145,    95],
       [  645,   662,     8, ...,     7,   129,   113],
       ..., 
       [  529,   443, 17793, ...,     4,  3586,     2],
       [  286,  1814,    23, ...,    12,     9,    23],
       [   97,    90,    35, ...,   204,   131,     9]], dtype=int32)

## One hot encoding

In [18]:
from keras.utils import to_categorical

In [19]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [20]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [21]:
Y_train = to_categorical(y_train, num_classes)
Y_train.shape

(60000, 10)

In [22]:
Y_train

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.]], dtype=float32)

In [23]:
np.unique(Y_train)

array([ 0.,  1.], dtype=float32)

In [24]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [25]:
np.unique(y_test)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [26]:
y_train3

array([[6],
       [9],
       [9],
       ..., 
       [9],
       [1],
       [1]], dtype=uint8)

In [27]:
np.unique(y_train3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [28]:
Y_train3 = to_categorical(y_train3, num_classes)
Y_train3.shape

(50000, 10)

In [29]:
Y_train3

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  1.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.]], dtype=float32)

In [30]:
np.unique(Y_train3)

array([ 0.,  1.], dtype=float32)

## Train and test set